name: newkids-web
services:
  web:
    container_name: wordpress
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - 2020:80
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG : ${WORDPRESS_DEBUG}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'http://localhost:2020');
        define('WP_HOME', 'http://localhost:2020');
    volumes:
      - ./.source/themes/:/var/www/html/wp-content/themes/
      - ./.source/plugins/:/var/www/html/wp-content/plugins/
      - ./.source/uploads/:/var/www/html/wp-content/uploads/
    networks:
      - newkids_network
  db:
    container_name: database
    image: mariadb:11.3.2
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - newkids_network
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/data/:/var/lib/mysql/
      - ./.docker/mysql/backup/:/docker-entrypoint-initdb.d/
  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - db
    networks:
      - newkids_network
    ports:
      - 1014:8080
    environment:
      UPLOAD_LIMIT: 999M
networks:
  newkids_network:
    driver: bridge
